apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-nodejs-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: app.demo-devopsdevsujofiart.online
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: demo-devops-nodejs-service
            port:
              number: 80