apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-nodejs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  rules:
  - host: app.demo-devopsdevsujofiart.online
    http:
      paths:
      - pathType: Prefix
        path: "/api/users/"
        backend:
          servicename: demo-devops-nodejs-service
          serviceport: 80