apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-nodejs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  rules:
  - host: app.demo-devopsdevsujofiart.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-devops-nodejs-service
            port:
              number: 80